FROM maven:3.6.0-jdk-8 AS build
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean package

FROM adoptopenjdk/openjdk8:latest
RUN mkdir /tmp/exports
COPY --from=build /usr/src/app/target/fly-0.0.1-SNAPSHOT.jar /app.jar
ENTRYPOINT [ "sh", "-c", "java -Dspring.profiles.active=docker -jar /app.jar" ]
