version: "2.1"
services:
  mysqlfly:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=immfly
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  application:
    image: fly-ws:latest
    container_name: fly-ws
    volumes:
      - ./exports:/tmp/exports

    environment:
          - MYSQL_ROOT_PASSWORD=admin
          - MYSQL_DATABASE=immfly
          - MYSQL_HOST=mysqlfly
          - MYSQL_PORT=3306
    ports:
      - "8080:8080"
    depends_on:
      mysqlfly:
        condition: service_healthy
